### ISSUE TITLE
additional tests for verifytree

### ISSUE THREAD

**Issue by dericed** [mediamicroservices/mm#112]
- test for presence of a capture.log

- no filenames contain colons

- test that there's not a package within a package

The last one could be done with `/tree/directory/directory[@name='objects']//directory[@name='objects']` since that would find when an `objects` directory is somewhere within the official `objects` directory.

**Comment by savcampbell** [comment]
Added in #111

**Comment by retokromer** [comment]
@dericed I guess this one can be closed, or am I missing something?

**Comment by dericed** [comment]
works for me
