### ISSUE TITLE
warn when file to ingest is still being written

### ISSUE THREAD

**Issue by dericed** [mediamicroservices/mm#117]
sometimes ingestfile is run on a file that is still being written to disk, so the initial rsync of that file into the package is incomplete. A warning should be added to note when this is happening, potentially the modification date could be tested to see if it is equal to now, or perhaps after the initial rsync is run another rsync could follow to ensure that the second rsync is not necessary.

**Comment by privatezero** [comment]
added in https://github.com/mediamicroservices/mm/commit/89e12b0e4b862da706742ded582eb13a3b73387e
