### ISSUE TITLE
overlapping variables with ltopers

### ISSUE THREAD

**Issue by privatezero** [mediamicroservices/mm#118]
In mmfunctions the check for mmconfig uses the same variable as the check for ltoper.conf.  

https://github.com/mediamicroservices/mm/blob/master/mmfunctions#L17

This results in errors when using mmfunctions independent of ltopers.  I propose the check for ltoper.conf be removed from mmfunctions (as it is related to a different repo).  Does this seem appropriate?

**Comment by dericed** [comment]
so appropriate

**Comment by privatezero** [comment]
Coolio! Took it out in https://github.com/mediamicroservices/mm/commit/64dd7c1ab69b03ccee741c8c850dafb9d18b7829!

**Comment by privatezero** [comment]
Merged, so closing!
