### ISSUE TITLE
v2.4.7 fails on Linuxbrew

### ISSUE THREAD

**Issue by retokromer** [mediamicroservices/mm#216]
FYI:

![screenshot from 2018-02-20 19-59-34](https://user-images.githubusercontent.com/3246607/36443535-58366ce0-1679-11e8-9e0e-4f3cce4d4133.png)

(On a fresh Ubuntu 16.04.3 LTS installation.)

**Comment by dericed** [comment]
does running `brew install perl` help?

**Comment by retokromer** [comment]
No. (Perl 5.26.1 is actually installed.)

I have to check which version was working on Linuxbrew as well. In fact, I presume I missed one or two releases on the Linux side, because `mm` is not included in our automated updates.

**Comment by retokromer** [comment]
FYI: The last one that we did install successfully with Linuxbrew at the lab is `2.3.1`.

**Comment by retokromer** [comment]
**Update:** Perl 5.26.1 revision 1 for Linuxbrew solves one issue, and now an error is goffice related:

<img width="731" alt="bildschirmfoto 2018-03-03 um 19 52 12" src="https://user-images.githubusercontent.com/3246607/36938075-9e9289e8-1f1c-11e8-93e0-45c011338cdf.png">

**Comment by retokromer** [comment]
We have switched back to an older version, which works on Linuxbrew as well.

**Comment by dericed** [comment]
Based on the comment at https://github.com/amiaopensource/ltopers/issues/181#issuecomment-385754038, I think this issue was closed without any resolution. Reopening.

**Comment by retokromer** [comment]
My report was related to `2.4.3` which is deprecated by `2.4.4`. I didn’t had the time to test the current version yet.

**Comment by retokromer** [comment]
FYI @dericed: I just tried to install `2.4.4`. Now there is an issue with `meson-internal`, an `mm` dependency: no module named `setuptools` could be found. I’m afraid, I don’t have the time to delve into this now.

**Comment by retokromer** [comment]
FYI @dericed: I just tried to install `2.4.5` as well. If I can find the time, I will make a PR for a fix on `tnftp`, then it should work again on a standard installation.

**Comment by retokromer** [comment]
FYI @dericed: `tnftp` works now, but there is still an error in the configuration file (the package `atk`, required by `gtk+-3.0` cannot be found). Of course, it’s possible to install, but not for a λ user, I guess.

**Comment by retokromer** [comment]
Closing, because seems not to be of interest.
