### ISSUE TITLE
store/usr audiomap setting in capture.log

### ISSUE THREAD

**Issue by dericed** [mediamicroservices/mm#228]
During ingestfile's interview, the operator can set an audio map strategy to override the default handling (such as only using the left channel to remap a stereo output). This setting is never stored so applying a later microservice to the package doesn't re-use that setting. I propose that the audio map is stored in capture log and re-read and use in makederiv if makederiv is using the original object as a source. This would be similar to how intime/outtime are stored in capture log and applied when the objects files is processed.

**Comment by aeschweik** [comment]
closed in #230
