### ISSUE TITLE
Captioning files get auto delivered to destinations upon completion

### ISSUE THREAD

**Issue by dinahhandel** [mediamicroservices/mm#23]
Maybe this wouldn't be that useful, but perhaps it is possible to set up an automatic delivery of the .scc and .src files to their destinations.

**Comment by dericed** [comment]
The destination is a bit of a moving target, sometimes by the time the scc is completed the package is on the server or may be on lto tape.

**Comment by dinahhandel** [comment]
I'm not so sure this would be a useful functionality to work on anymore, considering that our captioning workflow has changed and involves many more people creating and delivering scc/src files. If it's OK with @dericed and @CSchloss385 I would like to close this issue.

**Comment by dericed** [comment]
+1
