### ISSUE TITLE
combine restructureforcompliance and finishpackage into one script

### ISSUE THREAD

**Issue by dinahhandel** [mediamicroservices/mm#25]
Following digitization, two separate scripts are called to correct in and out times and create the archival package. These two scripts could be combined into one script that completes the digitization process.

**Comment by dericed** [comment]
@CSchloss385, any ideas for this?

**Comment by dinahhandel** [comment]
New idea: create option within ingest file that performs same tasks as RestructureforCompliance (asks for in/out times)

**Comment by dinahhandel** [comment]
This functionality has been added to ingest file, see the following commits: ef14cc6, f0faef9, 5f7a7a8, and c765b73.

**Comment by dinahhandel** [comment]
JUST KIDDING

**Comment by dinahhandel** [comment]
hopefully with  e117756 commit this issue should be closed.
