### ISSUE TITLE
AIPUpgrade upgrades

### ISSUE THREAD

**Issue by dinahhandel** [mediamicroservices/mm#42]
AIPUpgrade needs enhanced functionality. In addition to removing the submissionDocumentation directory, it needs to ask and log package type to the capture log (if there is no capture log, it should create one), and remove .DS_Store files.

**Comment by dericed** [comment]
I suggest lowercase `aipupgrade` to be consistent with the other scripts. `aipupgrade` could also include a new run of makemetadata.

**Comment by dinahhandel** [comment]
:+1:

**Comment by dinahhandel** [comment]
package type terms:
Production
Preservation-Video
Preservation-Document
Preservation-Audio
Unedited

**Comment by dinahhandel** [comment]
'aipupgrade' has all upgrades (remove submissionDocumentation directory, remove .DSstore files, log package type and capture log creation process, make new metadata) as of  7b6afae. Not closing issue yet because there could be further upgrades made to script down the line.

**Comment by dinahhandel** [comment]
modify aipupgrade so that the user only has to choose the package type once and it will apply to all packages that are input

**Comment by dinahhandel** [comment]
upgraded aipupgrade in 0d9e7c3

**Comment by dinahhandel** [comment]
@dericed ok to close for now?

**Comment by dericed** [comment]
B)
