### ISSUE TITLE
add frame md5s to makebroadcast

### ISSUE THREAD

**Issue by dinahhandel** [mediamicroservices/mm#47]
have makebroadcast add frame md5s to input. @CSchloss385 would you be willing to share your framemd5 command with me?

**Comment by CSchloss385** [comment]
@dinahhandel Sure! It's really short. This is what I usually use: ffmpeg -i input.mov -an -f framemd5 output.framemd5.

**Comment by dinahhandel** [comment]
frame md5s are integrated into makebroadcast as of  d260d54
