### ISSUE TITLE
makelossless is not working properly

### ISSUE THREAD

**Issue by dinahhandel** [mediamicroservices/mm#48]
makelossless is not able to run. @CSchloss385 will you post the terminal output that you get when you try to run it?

**Comment by CSchloss385** [comment]
@dinahhandel here is the error message I get when i run makelossless "CT 2-25-14Richard Ravitch.mov is not 2vuy or v210 or progressive ffv1, skipping." The input file is Apple ProRes, but I also get this message when I run it on an uncompressed 10 bit file.
