### ISSUE TITLE
Error: No such file or directory - migratefiles

### ISSUE THREAD

**Issue by retokromer** [mediamicroservices/mm#49]
When trying to install mediamicroservices/mm/mm version 1.1.6_2.

**Comment by dericed** [comment]
full output please

**Comment by retokromer** [comment]
$ brew upgrade
==> Upgrading 1 outdated package, with result:
mediamicroservices/mm/mm 1.1.6_2
==> Upgrading mediamicroservices/mm/mm
==> Downloading https://github.com/mediamicroservices/mm/archive/mm_v1.1.6.zip
Already downloaded: /Library/Caches/Homebrew/mm-1.1.6.zip
Error: No such file or directory - migratefiles

**Comment by NMAAHC** [comment]
same on new install:
≈:≈ brew install mediamicroservices/mm/mm
==> Installing mm from mediamicroservices/mm
==> Downloading https://github.com/mediamicroservices/mm/archive/mm_v1.1.6.zip
Already downloaded: /Library/Caches/Homebrew/mm-1.1.6.zip
Error: No such file or directory - migratefiles

**Comment by dinahhandel** [comment]
Should be fixed with 20a5c3c

**Comment by NMAAHC** [comment]
Thanks!

**Comment by retokromer** [comment]
Now works fine. Thanks!
