### ISSUE TITLE
develop QC tests script

### ISSUE THREAD

**Issue by dinahhandel** [mediamicroservices/mm#53]
create qc test script that has all qc functions in one script.

**Comment by dinahhandel** [comment]
script created as of d74766f but issue will stay open as more testing functions could be added in the future, or the reporting mechanisms of the script could be enhanced.

**Comment by dinahhandel** [comment]
@dericed thoughts about additions to the script or where it might fit into the workflow? Otherwise I'd like to close the issue for now.

**Comment by dinahhandel** [comment]
@dericed

**Comment by dericed** [comment]
ya let's close, integration of this is tbd
