### ISSUE TITLE
Wishlist - restructureForComplicance - assume file name for Media ID, batch restructure

### ISSUE THREAD

**Issue by NMAAHC** [mediamicroservices/mm#55]
Have flag for Media ID to assume name of file being restructured, not including file extension.

Also a flag to ignore INTIME and OUTIME.

With both of these flags could we then have the ability to run restructureForCompliance on multiple files at once?

**Comment by dinahhandel** [comment]
Unfortunately, restructureforcompliance is no longer actively being used or developed. What are you trying to use it for? It is possible that another script could suit your needs. We replaced it in our workflow with ingestfile -p, which creates an AIP according to our specifications and accounts for setting in and out times and digitization logs. I can still try to look into adding this functionality to restructure for compliance next week, as it shouldn't be too complicated...

**Comment by dinahhandel** [comment]
Whoops, I forgot to mention you, @NMAAHC ! So, I am looking at the script now, and adding a while loop so that you can process multiple inputs at a time. I can set the media id as the file name easily- do you need in and out times at all? If not, perhaps I can remove them, since we don't use this script and therefore don't need them anymore.

**Comment by dinahhandel** [comment]
Hi @NMAAHC I made edits to the script based on your needs- I won't be making a new release of mm for a bit longer though... To test, I recommend either copying and pasting the script from github into the current version of the script in your /usr/local/bin/ (I can give you more detailed instructions if needed), or try to install the head version of media microservices by typing brew install --force mediamicroservices/mm/mm --HEAD (I think that should work... @dericed ?)

**Comment by NMAAHC** [comment]
@dinahhandel  Thank you!

We will look into ingestfile, as well. restructureforcompliance is part of our workflow at the moment but we modify to catch up with the current mm workflow. in the meantime, the edits you made will be very helpful.

The best place to understand ingestfile and the current mm workflow is here on github in the mm documentation and your NDSR blog?

**Comment by dinahhandel** [comment]
@NMAAHC great! I think you will find that with the modifications you can use restructureforcompliance and you don't need ingestfile. ingestfile is essentially the same as finishpackage, but more extensive in that you set up processing and delivery directories beforehand, the filename of the derivatives has to adhere to specific rules (uppercase, no spaces or special characters, and can include numbers), and it only works with a file input whereas finishpackage is a directory input. You'd have to create the mmconfig file if you haven't and set the minimum directories... 

Definitely look into the readme and feel free to ask me any questions! I'm going to close this issue for now, but let me know too if you have any trouble with the new restructureforcompliance (again, it isn't in a new release so you have to copy paste the script from github into your local version, or install the HEAD version of mm).
