### ISSUE TITLE
makemetatadata - warning: failed to load external entity

### ISSUE THREAD

**Issue by NMAAHC** [mediamicroservices/mm#59]
Script appears to be working fine, so I'm wondering why it is giving this warning. 

/Users/medialab
≈:≈ makemetadata /Volumes/06a_SD_Video_01/_COLLECTIONS/2012_79_Pearl_Bowser/AIPS/2012_79_2_269_1a__PM /Volumes/06a_SD_Video_01/_COLLECTIONS/2012_79_Pearl_Bowser/AIPS/2012_79_2_270_1a__PM 
  2016-07-07T12:45:32 - Making metadata reports for /Volumes/06a_SD_Video_01/_COLLECTIONS/2012_79_Pearl_Bowser/AIPS/2012_79_2_269_1a__PM.
  [makemetadata] 2016-07-07T12:45:32 - Running: mkdir -p ./metadata/fileMeta/./objects
warning: failed to load external entity "/Volumes/06a_SD_Video_01/_COLLECTIONS/2012_79_Pearl_Bowser/AIPS/2012_79_2_269_1a__PM/metadata/fileMeta/.DS_Store_mediainfo.xml"
warning: failed to load external entity "/Volumes/06a_SD_Video_01/_COLLECTIONS/2012_79_Pearl_Bowser/AIPS/2012_79_2_269_1a__PM/metadata/fileMeta/metadata/fileMeta/objects/2012_79_2_269_1a__PM.mov_exiftool.xml_mediainfo.xml"
warning: failed to load external entity "/Volumes/06a_SD_Video_01/_COLLECTIONS/2012_79_Pearl_Bowser/AIPS/2012_79_2_269_1a__PM/metadata/fileMeta/metadata/fileMeta/objects/2012_79_2_269_1a__PM.mov_ffprobe.xml_mediainfo.xml"
warning: failed to load external entity "/Volumes/06a_SD_Video_01/_COLLECTIONS/2012_79_Pearl_Bowser/AIPS/2012_79_2_269_1a__PM/metadata/fileMeta/metadata/fileMeta/objects/2012_79_2_269_1a__PM.mov_mediainfo.xml_mediainfo.xml"
warning: failed to load external entity "/Volumes/06a_SD_Video_01/_COLLECTIONS/2012_79_Pearl_Bowser/AIPS/2012_79_2_269_1a__PM/metadata/fileMeta/metadata/fileMeta/objects/2012_79_2_269_1a__PM.mov_mediatrace.xml_mediainfo.xml"
  [makemetadata] 2016-07-07T12:45:34 - Running: rm -r -f /tmp/makemetadata.DZbrYZ
  2016-07-07T12:45:34 - Making metadata reports for /Volumes/06a_SD_Video_01/_COLLECTIONS/2012_79_Pearl_Bowser/AIPS/2012_79_2_270_1a__PM.
  [makemetadata] 2016-07-07T12:45:34 - Running: mkdir -p ./metadata/fileMeta/./objects
warning: failed to load external entity "/Volumes/06a_SD_Video_01/_COLLECTIONS/2012_79_Pearl_Bowser/AIPS/2012_79_2_270_1a__PM/metadata/fileMeta/.DS_Store_mediainfo.xml"
warning: failed to load external entity "/Volumes/06a_SD_Video_01/_COLLECTIONS/2012_79_Pearl_Bowser/AIPS/2012_79_2_270_1a__PM/metadata/fileMeta/metadata/fileMeta/objects/2012_79_2_270_1a__PM.mov_exiftool.xml_mediainfo.xml"
warning: failed to load external entity "/Volumes/06a_SD_Video_01/_COLLECTIONS/2012_79_Pearl_Bowser/AIPS/2012_79_2_270_1a__PM/metadata/fileMeta/metadata/fileMeta/objects/2012_79_2_270_1a__PM.mov_ffprobe.xml_mediainfo.xml"
warning: failed to load external entity "/Volumes/06a_SD_Video_01/_COLLECTIONS/2012_79_Pearl_Bowser/AIPS/2012_79_2_270_1a__PM/metadata/fileMeta/metadata/fileMeta/objects/2012_79_2_270_1a__PM.mov_mediainfo.xml_mediainfo.xml"
warning: failed to load external entity "/Volumes/06a_SD_Video_01/_COLLECTIONS/2012_79_Pearl_Bowser/AIPS/2012_79_2_270_1a__PM/metadata/fileMeta/metadata/fileMeta/objects/2012_79_2_270_1a__PM.mov_mediatrace.xml_mediainfo.xml"
  [makemetadata] 2016-07-07T12:45:35 - Running: rm -r -f /tmp/makemetadata.YZKOL4

**Comment by dericed** [comment]
only because I'm lazy. The process to wrap metadata in METS looks for metadata for all the files, but obviously some files should have a metadata file (or there would be a loop), so there's an error when it looks for anticipated metadata. I should adjust it.

**Comment by NMAAHC** [comment]
ok. is that why the METS file is separated from the other object meta
![screen shot 2016-07-07 at 1 00 25 pm](https://cloud.githubusercontent.com/assets/15135491/16661859/f6cca2a8-4442-11e6-8cf7-0fe5dc49d64e.png)
data files -

**Comment by dericed** [comment]
don't metadata that metadata

**Comment by NMAAHC** [comment]
\m/

**Comment by dericed** [comment]
fixed in https://github.com/mediamicroservices/mm/issues/80
