### ISSUE TITLE
mp3 normalization

### ISSUE THREAD

**Issue by privatezero** [mediamicroservices/mm#85]
In testing it appears that normalization tool called by makemp3 is possibly WAV specific and isn't actually doing anything (apart from making it look like normalization is occurring).  Might need to investigate alternate method of normalization.

**Comment by privatezero** [comment]
After looking into this a bit more it seems that volume adjustment for mp3s generated with this tool is achieved by manipulating metadata tags.  This would account for the volume discrepancy when playing via different players as well as the unchanged waveform.  If this is acceptable (as opposed to actually normalizing the waveform) then we can close this.

**Comment by dericed** [comment]
hmmm, should we remove or change the normalization step then. The mp3s can be used in voice-to-text transformation so presumably a reasonable volume may have an impact on that.

**Comment by privatezero** [comment]
Yeah- there is something that makes me a little nervous about controlling normalization via metadata tags as opposed to actually normalizing. Seems like a risk for interoperability!

Off the top of my head there are a couple of ways that this could be changed.  We could use the dynamic normalization filter in ffmpeg. I have experimented a bit with this and it seems to have cool potential for spoken word, but at its default settings runs the risk of slightly messing with the dynamic range of music.  I am using it in my audio scripts at a slightly less aggressive setting that I think mostly takes care of this, but it still is making some changes I am sure.  If these files are primarily used for voice-to-text (thus making slight dynamic changes in music not an issue) this probably would be the best method.

We could also do a two pass combination of ffmpeg volumedetect and then use the output from that to do a static gain boost.  This would take more time though as to my knowledge it is impossible to do this in a single pass with ffmpeg.

I know sox has some normalization features as well, but not sure if it is dynamic or single pass etc.

**Comment by privatezero** [comment]
Because of current use of mp3s, this doesn't currently seem to be an issue.  Gonna close for now!
