### ISSUE TITLE
permission error on dbbackup

### ISSUE THREAD

**Issue by dericed** [mediamicroservices/mm#88]
```
dbbackup 
mysqldump: Got error: 1045: Access denied for user 'archivesx'@'localhost' (using password: NO) when trying to connect
```

**Comment by privatezero** [comment]
I believe this can be solved with better documentation on the necessity of using mysql_config_editor to create a profile specifically for backups should the host computer and user computer not be the same. Perhaps the script can be modified to help facilitate this process in the manner of the createpremisdb script. (Albeit minus the soothing yellow instructions).

On a related note- in looking into this, I believe I am able to answer the question of whether or not the DB name can be baked into the login configuration used in mmconfig.  Looks like mysql_config_editor only really supports the storage of login credentials, so the user will still have to manually enter the DB name in mmconfig.

See: ['my_sql_config_editor' manpage](http://www.manpagez.com/man/1/mysql_config_editor/mysql_config_editor-5.6.22.php)

**Comment by privatezero** [comment]
Changes made in https://github.com/mediamicroservices/mm/commit/a6a68ee59372e47fd687dbc31e8d51510759391a should resolve these issues!
