### ISSUE TITLE
no gold-colored warnings

### ISSUE THREAD

**Issue by dericed** [mediamicroservices/mm#89]
just no

NO

**Comment by privatezero** [comment]
😞

**Comment by privatezero** [comment]
I assumed that also ruled out teal. This is attention getting! https://github.com/mediamicroservices/mm/commit/69b7f3f5c3da37ad5a760f075a43f2208ea189da

![image](https://cloud.githubusercontent.com/assets/12941699/20447013/857b3c0a-adaa-11e6-91c5-8965ab04fbf5.png)

**Comment by dericed** [comment]
teal is bearable

**Comment by dinahhandel** [comment]
Dave I never knew you felt so strongly about color choices!

**Comment by ablwr** [comment]
https://thecreativeindependent.com/people/laurie-anderson-on-reality-and-non-reality/

**Comment by privatezero** [comment]
Gonna close this- I thiiiiiink i found 'em all. The colored text is dead. Long live the colored text.

**Comment by dericed** [comment]
```
                                                               
   m    #                    #                                 
 mm#mm  # mm    mmm   m mm   #   m         m   m   mmm   m   m 
   #    #"  #  "   #  #"  #  # m"          "m m"  #" "#  #   # 
   #    #   #  m"""#  #   #  #"#            #m#   #   #  #   # 
   "mm  #   #  "mm"#  #   #  #  "m          "#    "#m#"  "mm"# 
                                            m"                 
                                           ""   
```
