### ISSUE TITLE
in premis db add primary/foreign key relationships

### ISSUE THREAD

**Issue by dericed** [mediamicroservices/mm#90]
For instance, if should be feasible to relate from a fixity record back to its corresponding event record, currently the match on timestamp doesn't fully work, since it takes longer than 1 second to checksum.

**Comment by privatezero** [comment]
Currently there are primary/foreign key relationships between the objectIdentifierValue columns in the fixity and event tables and the objectIdentifierValue in the object table.  I'll look into if queries can be formed to tie those records together using existing relationships.

Another option may be to integrate something similar to the way the _eventoutcome_update function queries the database for the ID of the last event and then assigns that to a variable.  This could theoretically be adapted and added to a new column in the fixity table, but might have the potential to introduce a bit of ambiguity in the process.

**Comment by privatezero** [comment]
Made changes to fixity reporting in https://github.com/mediamicroservices/mm/commit/212a85d0a3952351dee7c1fc7c4a9aba3134f9b9 that include the Event Identifier associated with the fixity event.   This will require altering the existing database with the following commands:
`ALTER TABLE fixity ADD eventIdentifierValue bigint NOT NULL AFTER fixityIdentifierValue;`
`SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE fixity
ADD FOREIGN KEY (eventIdentifierValue)
REFERENCES event(eventIdentifierValue);
SET FOREIGN_KEY_CHECKS=1;`

**Comment by privatezero** [comment]
Merged in https://github.com/mediamicroservices/mm/releases/tag/mm_v2.1.8.  Closing!
