### ISSUE TITLE
README license

### ISSUE THREAD

**Issue by privatezero** [mediamicroservices/mm#97]
Similar to the discussion relating to the vrecord documentation- would it be appropriate to have some type of license explicitly associated with the mm documentation?

**Comment by dericed** [comment]
The documentation would be under the MIT license of the repo, though some CC licenses would not conflict with that. Which CC license is NDSR using?

**Comment by privatezero** [comment]
Hmmmm-don't properly know actually! I can't speak for last year's terms, but I do seem to recall a clause in this year's contract stating that all work is the property of the host institution, so anything I contribute should be covered by CUNY's policy!

**Comment by dericed** [comment]
I looked it up: CC Attribution NonCommercial 4.0 International License.

**Comment by privatezero** [comment]
added license link to README in https://github.com/mediamicroservices/mm/commit/aca7702f72b879d8a439430ed6aa66af56e31236
